spring:
  application:
    name: pm-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  # spring will setup and update our db schema
  jpa:
    hibernate:
      ddl-auto: update
